package pl.com.app;


import pl.com.app.dto.*;
import pl.com.app.repository.model.enums.EGuarantee;
import pl.com.app.repository.model.enums.EPayment;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;

public class ModelsData {

    public static List<CountryDTO> getCountries(){
        return Arrays.asList(
                CountryDTO.builder().name("POLSKA").build(),
                CountryDTO.builder().name("NIEMCY").build(),
                CountryDTO.builder().name("USA").build(),
                CountryDTO.builder().name("CHINY").build(),
                CountryDTO.builder().name("AUSTRALIA").build(),
                CountryDTO.builder().name("HISZPANIA").build(),
                CountryDTO.builder().name("FRANCJA").build(),
                CountryDTO.builder().name("LITWA").build(),
                CountryDTO.builder().name("ROSJA").build(),
                CountryDTO.builder().name("KOREA").build()
        );
    }

    public static List<TradeDTO> getTrades(){
        return Arrays.asList(
                TradeDTO.builder().name("PRZEMYSL").build(),
                TradeDTO.builder().name("ROLNICTWO").build(),
                TradeDTO.builder().name("TRANSPORT").build(),
                TradeDTO.builder().name("HANDEL").build(),
                TradeDTO.builder().name("NAUKA").build(),
                TradeDTO.builder().name("KULTURA").build(),
                TradeDTO.builder().name("ZDROWIE").build()
        );
    }

    public static List<PaymentDTO> getPayments(){
        return Arrays.asList(
                PaymentDTO.builder().ePayment(EPayment.CASH).build(),
                PaymentDTO.builder().ePayment(EPayment.CARD).build(),
                PaymentDTO.builder().ePayment(EPayment.MONEY_TRANSFER).build()
        );
    }

    public static List<CustomerDTO> getCustomers() {
        return Arrays.asList(
                CustomerDTO.builder()
                        .name("KAROL")
                        .surname("DERDA")
                        .birthDate(LocalDate.of(1991, 12, 1))
                        .countryDTO(CountryDTO.builder().name("POLSKA").build())
                        .build(),
                CustomerDTO.builder()
                        .name("KASIA")
                        .surname("MOTORSKA")
                        .birthDate(LocalDate.of(1990, 11, 2))
                        .countryDTO(CountryDTO.builder().name("POLSKA").build())
                        .build(),
                CustomerDTO.builder()
                        .name("KASIA")
                        .surname("GAWRYLUK")
                        .birthDate(LocalDate.of(1992, 1, 1))
                        .countryDTO(CountryDTO.builder().name("NIEMCY").build())
                        .build(),
                CustomerDTO.builder()
                        .name("OLA")
                        .surname("GLOWICKA")
                        .birthDate(LocalDate.of(1993, 4, 12))
                        .countryDTO(CountryDTO.builder().name("NIEMCY").build())
                        .build(),
                CustomerDTO.builder()
                        .name("ALA")
                        .surname("KISZLO")
                        .birthDate(LocalDate.of(1994, 4, 3))
                        .countryDTO(CountryDTO.builder().name("USA").build())
                        .build(),
                CustomerDTO.builder()
                        .name("PAWEL")
                        .surname("WARCHOL")
                        .birthDate(LocalDate.of(1995, 3, 8))
                        .countryDTO(CountryDTO.builder().name("USA").build())
                        .build(),
                CustomerDTO.builder()
                        .name("WOJTEK")
                        .surname("GRYSIAK")
                        .birthDate(LocalDate.of(1981, 3, 30))
                        .countryDTO(CountryDTO.builder().name("CHINY").build())
                        .build(),
                CustomerDTO.builder()
                        .name("ZBYSZEK")
                        .surname("TOMASZEWSKI")
                        .birthDate(LocalDate.of(1981, 3, 28))
                        .countryDTO(CountryDTO.builder().name("AUSTRALIA").build())
                        .build(),
                CustomerDTO.builder()
                        .name("ALEKS")
                        .surname("NOWAK")
                        .birthDate(LocalDate.of(1971, 2, 23))
                        .countryDTO(CountryDTO.builder().name("AUSTRALIA").build())
                        .build(),
                CustomerDTO.builder()
                        .name("FRANEK")
                        .surname("KOWAL")
                        .birthDate(LocalDate.of(1999, 2, 16))
                        .countryDTO(CountryDTO.builder().name("AUSTRALIA").build())
                        .build(),
                CustomerDTO.builder()
                        .name("MARCIN")
                        .surname("KOWAL")
                        .birthDate(LocalDate.of(1995, 1, 19))
                        .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                        .build()
        );
    }

    public static List<CategoryDTO> getCategories(){
        return Arrays.asList(
                CategoryDTO.builder().name("IT").build(),
                CategoryDTO.builder().name("SAMOCHODY").build(),
                CategoryDTO.builder().name("ELEKTRONIKA").build(),
                CategoryDTO.builder().name("MEBLE").build(),
                CategoryDTO.builder().name("SPRZET").build(),
                CategoryDTO.builder().name("ZIARNA").build(),
                CategoryDTO.builder().name("OWOCE").build(),
                CategoryDTO.builder().name("WARZYWA").build(),
                CategoryDTO.builder().name("NAPOJE").build()
        );
    }

    public static List<ProducerDTO> getProducers() {
        return Arrays.asList(
                ProducerDTO.builder()
                        .name("LMED")
                        .countryDTO(CountryDTO.builder().name("KOREA").build())
                        .tradeDTO(TradeDTO.builder().name("PRZEMYSL").build())
                        .build(),
                ProducerDTO.builder()
                        .name("IT TECH")
                        .countryDTO(CountryDTO.builder().name("KOREA").build())
                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                        .build(),
                ProducerDTO.builder()
                        .name("DISCOVER")
                        .countryDTO(CountryDTO.builder().name("ROSJA").build())
                        .tradeDTO(TradeDTO.builder().name("TRANSPORT").build())
                        .build(),
                ProducerDTO.builder()
                        .name("VEGE TECH")
                        .countryDTO(CountryDTO.builder().name("NIEMCY").build())
                        .tradeDTO(TradeDTO.builder().name("HANDEL").build())
                        .build(),
                ProducerDTO.builder()
                        .name("UNIX")
                        .countryDTO(CountryDTO.builder().name("LITWA").build())
                        .tradeDTO(TradeDTO.builder().name("NAUKA").build())
                        .build(),
                ProducerDTO.builder()
                        .name("TOOTSIE")
                        .countryDTO(CountryDTO.builder().name("LITWA").build())
                        .tradeDTO(TradeDTO.builder().name("KULTURA").build())
                        .build(),
                ProducerDTO.builder()
                        .name("NEW SYSTEM")
                        .countryDTO(CountryDTO.builder().name("FRANCJA").build())
                        .tradeDTO(TradeDTO.builder().name("ZDROWIE").build())
                        .build(),
                ProducerDTO.builder()
                        .name("MISIO")
                        .countryDTO(CountryDTO.builder().name("AUSTRALIA").build())
                        .tradeDTO(TradeDTO.builder().name("PRZEMYSL").build())
                        .build(),
                ProducerDTO.builder()
                        .name("LOGGUS")
                        .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                        .build()
        );
    }

    public static List<ShopDTO> getShops() {
        return Arrays.asList(
                ShopDTO.builder()
                        .name("LMED")
                        .countryDTO(CountryDTO.builder().name("KOREA").build())
                        .build(),
                ShopDTO.builder()
                        .name("IT TECH")
                        .countryDTO(CountryDTO.builder().name("POLSKA").build())
                        .build(),
                ShopDTO.builder()
                        .name("DISCOVER")
                        .countryDTO(CountryDTO.builder().name("ROSJA").build())
                        .build(),
                ShopDTO.builder()
                        .name("VEGE TECH")
                        .countryDTO(CountryDTO.builder().name("CHINY").build())
                        .build(),
                ShopDTO.builder()
                        .name("UNIX")
                        .countryDTO(CountryDTO.builder().name("LITWA").build())
                        .build(),
                ShopDTO.builder()
                        .name("EVENT")
                        .countryDTO(CountryDTO.builder().name("AUSTRALIA").build())
                        .build()
        );
    }

    public static List<ProductDTO> getProducts() {
        return Arrays.asList(
                ProductDTO.builder()
                        .name("APLIKACJA")
                        .price(new BigDecimal(3223))
                        .categoryDTO(CategoryDTO.builder().name("IT").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("LOGGUS")
                                .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                .build())
                        .eGuarantees(new HashSet<>(Arrays.asList(EGuarantee.EXCHANGE)))
                        .build(),
                ProductDTO.builder()
                        .name("WODA")
                        .price(new BigDecimal(0.88))
                        .categoryDTO(CategoryDTO.builder().name("NAPOJE").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("LOGGUS")
                                .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                .build())
                        .eGuarantees(new HashSet<>(Arrays.asList(EGuarantee.EXCHANGE, EGuarantee.MONEY_BACK)))
                        .build(),
                ProductDTO.builder()
                        .name("NAPRAWA LAPTOPOW")
                        .price(new BigDecimal(54))
                        .categoryDTO(CategoryDTO.builder().name("IT").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("IT TECH")
                                .countryDTO(CountryDTO.builder().name("KOREA").build())
                                .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                .build())
                        .eGuarantees(new HashSet<>())
                        .build(),
                ProductDTO.builder()
                        .name("MALUCH")
                        .price(new BigDecimal(999))
                        .categoryDTO(CategoryDTO.builder().name("SAMOCHODY").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("IT TECH")
                                .countryDTO(CountryDTO.builder().name("KOREA").build())
                                .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                .build())
                        .eGuarantees(new HashSet<>(Arrays.asList(EGuarantee.SERVICE, EGuarantee.HELP_DESK)))
                        .build(),
                ProductDTO.builder()
                        .name("FIAT")
                        .price(new BigDecimal(9999))
                        .categoryDTO(CategoryDTO.builder().name("SAMOCHODY").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("DISCOVER")
                                .countryDTO(CountryDTO.builder().name("ROSJA").build())
                                .tradeDTO(TradeDTO.builder().name("TRANSPORT").build())
                                .build())
                        .eGuarantees(new HashSet<>())
                        .build(),
                ProductDTO.builder()
                        .name("MARCHEW")
                        .price(new BigDecimal(3.32))
                        .categoryDTO(CategoryDTO.builder().name("WARZYWA").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("DISCOVER")
                                .countryDTO(CountryDTO.builder().name("ROSJA").build())
                                .tradeDTO(TradeDTO.builder().name("TRANSPORT").build())
                                .build())
                        .eGuarantees(new HashSet<>(Arrays.asList(EGuarantee.SERVICE)))
                        .build(),
                ProductDTO.builder()
                        .name("BUS")
                        .price(new BigDecimal(14876))
                        .categoryDTO(CategoryDTO.builder().name("SAMOCHODY").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("VEGE TECH")
                                .countryDTO(CountryDTO.builder().name("NIEMCY").build())
                                .tradeDTO(TradeDTO.builder().name("HANDEL").build())
                                .build())
                        .eGuarantees(new HashSet<>(Arrays.asList(EGuarantee.MONEY_BACK)))
                        .build(),
                ProductDTO.builder()
                        .name("LAPTOP")
                        .price(new BigDecimal(4449.9))
                        .categoryDTO(CategoryDTO.builder().name("ELEKTRONIKA").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("VEGE TECH")
                                .countryDTO(CountryDTO.builder().name("NIEMCY").build())
                                .tradeDTO(TradeDTO.builder().name("HANDEL").build())
                                .build())
                        .eGuarantees(new HashSet<>(Arrays.asList(EGuarantee.EXCHANGE)))
                        .build(),
                ProductDTO.builder()
                        .name("KOMORKA")
                        .price(new BigDecimal(2998.77))
                        .categoryDTO(CategoryDTO.builder().name("ELEKTRONIKA").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("UNIX")
                                .countryDTO(CountryDTO.builder().name("LITWA").build())
                                .tradeDTO(TradeDTO.builder().name("NAUKA").build())
                                .build())
                        .eGuarantees(new HashSet<>(Arrays.asList(EGuarantee.EXCHANGE, EGuarantee.MONEY_BACK, EGuarantee.HELP_DESK)))
                        .build(),
                ProductDTO.builder()
                        .name("TELEWIZOR")
                        .price(new BigDecimal(1888.88))
                        .categoryDTO(CategoryDTO.builder().name("ELEKTRONIKA").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("UNIX")
                                .countryDTO(CountryDTO.builder().name("LITWA").build())
                                .tradeDTO(TradeDTO.builder().name("NAUKA").build())
                                .build())
                        .eGuarantees(new HashSet<>(Arrays.asList(EGuarantee.MONEY_BACK, EGuarantee.HELP_DESK)))
                        .build(),
                ProductDTO.builder()
                        .name("KOMODA")
                        .price(new BigDecimal(99.99))
                        .categoryDTO(CategoryDTO.builder().name("MEBLE").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("TOOTSIE")
                                .countryDTO(CountryDTO.builder().name("LITWA").build())
                                .tradeDTO(TradeDTO.builder().name("KULTURA").build())
                                .build())
                        .eGuarantees(new HashSet<>(Arrays.asList(EGuarantee.SERVICE, EGuarantee.HELP_DESK)))
                        .build(),
                ProductDTO.builder()
                        .name("SZAFA")
                        .price(new BigDecimal(654.02))
                        .categoryDTO(CategoryDTO.builder().name("MEBLE").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("TOOTSIE")
                                .countryDTO(CountryDTO.builder().name("LITWA").build())
                                .tradeDTO(TradeDTO.builder().name("KULTURA").build())
                                .build())
                        .eGuarantees(new HashSet<>(Arrays.asList(EGuarantee.HELP_DESK)))
                        .build(),
                ProductDTO.builder()
                        .name("ODKURZACZ")
                        .price(new BigDecimal(199.98))
                        .categoryDTO(CategoryDTO.builder().name("SPRZET").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("NEW SYSTEM")
                                .countryDTO(CountryDTO.builder().name("FRANCJA").build())
                                .tradeDTO(TradeDTO.builder().name("ZDROWIE").build())
                                .build())
                        .eGuarantees(new HashSet<>(Arrays.asList(EGuarantee.SERVICE)))
                        .build(),
                ProductDTO.builder()
                        .name("SLONECZNIK")
                        .price(new BigDecimal(11.11))
                        .categoryDTO(CategoryDTO.builder().name("ZIARNA").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("NEW SYSTEM")
                                .countryDTO(CountryDTO.builder().name("FRANCJA").build())
                                .tradeDTO(TradeDTO.builder().name("ZDROWIE").build())
                                .build())
                        .eGuarantees(new HashSet<>(Arrays.asList(EGuarantee.SERVICE, EGuarantee.MONEY_BACK, EGuarantee.HELP_DESK, EGuarantee.EXCHANGE)))
                        .build(),
                ProductDTO.builder()
                        .name("BANAN")
                        .price(new BigDecimal(8.76))
                        .categoryDTO(CategoryDTO.builder().name("OWOCE").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("MISIO")
                                .countryDTO(CountryDTO.builder().name("AUSTRALIA").build())
                                .tradeDTO(TradeDTO.builder().name("PRZEMYSL").build())
                                .build())
                        .eGuarantees(new HashSet<>(Arrays.asList(EGuarantee.SERVICE, EGuarantee.MONEY_BACK, EGuarantee.EXCHANGE)))
                        .build(),
                ProductDTO.builder()
                        .name("JABLKO")
                        .price(new BigDecimal(6.77))
                        .categoryDTO(CategoryDTO.builder().name("OWOCE").build())
                        .producerDTO(ProducerDTO.builder()
                                .name("LOGGUS")
                                .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                .build())
                        .eGuarantees(new HashSet<>(Arrays.asList(EGuarantee.SERVICE, EGuarantee.EXCHANGE)))
                        .build()
        );
    }

    public static List<StockDTO> getStocks() {
        return Arrays.asList(
                StockDTO.builder()
                        .quantity(11)
                        .productDTO(ProductDTO.builder()
                                .name("APLIKACJA")
                                .price(new BigDecimal(3223))
                                .categoryDTO(CategoryDTO.builder().name("IT").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("LOGGUS")
                                        .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("LMED")
                                .countryDTO(CountryDTO.builder().name("KOREA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(22)
                        .productDTO(ProductDTO.builder()
                                .name("APLIKACJA")
                                .price(new BigDecimal(3223))
                                .categoryDTO(CategoryDTO.builder().name("IT").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("LOGGUS")
                                        .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("IT TECH")
                                .countryDTO(CountryDTO.builder().name("POLSKA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(33)
                        .productDTO(ProductDTO.builder()
                                .name("WODA")
                                .price(new BigDecimal(0.88))
                                .categoryDTO(CategoryDTO.builder().name("NAPOJE").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("LOGGUS")
                                        .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("IT TECH")
                                .countryDTO(CountryDTO.builder().name("POLSKA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(44)
                        .productDTO(ProductDTO.builder()
                                .name("NAPRAWA LAPTOPOW")
                                .price(new BigDecimal(54))
                                .categoryDTO(CategoryDTO.builder().name("IT").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("IT TECH")
                                        .countryDTO(CountryDTO.builder().name("KOREA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("IT TECH")
                                .countryDTO(CountryDTO.builder().name("POLSKA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(55)
                        .productDTO(ProductDTO.builder()
                                .name("WODA")
                                .price(new BigDecimal(0.88))
                                .categoryDTO(CategoryDTO.builder().name("NAPOJE").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("LOGGUS")
                                        .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("DISCOVER")
                                .countryDTO(CountryDTO.builder().name("ROSJA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(66)
                        .productDTO(ProductDTO.builder()
                                .name("NAPRAWA LAPTOPOW")
                                .price(new BigDecimal(54))
                                .categoryDTO(CategoryDTO.builder().name("IT").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("IT TECH")
                                        .countryDTO(CountryDTO.builder().name("KOREA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("DISCOVER")
                                .countryDTO(CountryDTO.builder().name("ROSJA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(77)
                        .productDTO(ProductDTO.builder()
                                .name("MALUCH")
                                .price(new BigDecimal(999))
                                .categoryDTO(CategoryDTO.builder().name("SAMOCHODY").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("IT TECH")
                                        .countryDTO(CountryDTO.builder().name("KOREA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("DISCOVER")
                                .countryDTO(CountryDTO.builder().name("ROSJA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(88)
                        .productDTO(ProductDTO.builder()
                                .name("NAPRAWA LAPTOPOW")
                                .price(new BigDecimal(54))
                                .categoryDTO(CategoryDTO.builder().name("IT").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("IT TECH")
                                        .countryDTO(CountryDTO.builder().name("KOREA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("VEGE TECH")
                                .countryDTO(CountryDTO.builder().name("CHINY").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(3)
                        .productDTO(ProductDTO.builder()
                                .name("FIAT")
                                .price(new BigDecimal(9999))
                                .categoryDTO(CategoryDTO.builder().name("SAMOCHODY").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("DISCOVER")
                                        .countryDTO(CountryDTO.builder().name("ROSJA").build())
                                        .tradeDTO(TradeDTO.builder().name("TRANSPORT").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("VEGE TECH")
                                .countryDTO(CountryDTO.builder().name("CHINY").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(4)
                        .productDTO(ProductDTO.builder()
                                .name("MARCHEW")
                                .price(new BigDecimal(3.32))
                                .categoryDTO(CategoryDTO.builder().name("WARZYWA").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("DISCOVER")
                                        .countryDTO(CountryDTO.builder().name("ROSJA").build())
                                        .tradeDTO(TradeDTO.builder().name("TRANSPORT").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("VEGE TECH")
                                .countryDTO(CountryDTO.builder().name("CHINY").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(5)
                        .productDTO(ProductDTO.builder()
                                .name("BUS")
                                .price(new BigDecimal(14876))
                                .categoryDTO(CategoryDTO.builder().name("SAMOCHODY").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("VEGE TECH")
                                        .countryDTO(CountryDTO.builder().name("NIEMCY").build())
                                        .tradeDTO(TradeDTO.builder().name("HANDEL").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("VEGE TECH")
                                .countryDTO(CountryDTO.builder().name("CHINY").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(65)
                        .productDTO(ProductDTO.builder()
                                .name("MALUCH")
                                .price(new BigDecimal(999))
                                .categoryDTO(CategoryDTO.builder().name("SAMOCHODY").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("IT TECH")
                                        .countryDTO(CountryDTO.builder().name("KOREA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("UNIX")
                                .countryDTO(CountryDTO.builder().name("LITWA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(34)
                        .productDTO(ProductDTO.builder()
                                .name("FIAT")
                                .price(new BigDecimal(9999))
                                .categoryDTO(CategoryDTO.builder().name("SAMOCHODY").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("DISCOVER")
                                        .countryDTO(CountryDTO.builder().name("ROSJA").build())
                                        .tradeDTO(TradeDTO.builder().name("TRANSPORT").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("UNIX")
                                .countryDTO(CountryDTO.builder().name("LITWA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(23)
                        .productDTO(ProductDTO.builder()
                                .name("LAPTOP")
                                .price(new BigDecimal(4449.9))
                                .categoryDTO(CategoryDTO.builder().name("ELEKTRONIKA").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("VEGE TECH")
                                        .countryDTO(CountryDTO.builder().name("NIEMCY").build())
                                        .tradeDTO(TradeDTO.builder().name("HANDEL").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("UNIX")
                                .countryDTO(CountryDTO.builder().name("LITWA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(11)
                        .productDTO(ProductDTO.builder()
                                .name("KOMORKA")
                                .price(new BigDecimal(2998.77))
                                .categoryDTO(CategoryDTO.builder().name("ELEKTRONIKA").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("UNIX")
                                        .countryDTO(CountryDTO.builder().name("LITWA").build())
                                        .tradeDTO(TradeDTO.builder().name("NAUKA").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("UNIX")
                                .countryDTO(CountryDTO.builder().name("LITWA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(7)
                        .productDTO(ProductDTO.builder()
                                .name("TELEWIZOR")
                                .price(new BigDecimal(1888.88))
                                .categoryDTO(CategoryDTO.builder().name("ELEKTRONIKA").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("UNIX")
                                        .countryDTO(CountryDTO.builder().name("LITWA").build())
                                        .tradeDTO(TradeDTO.builder().name("NAUKA").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("UNIX")
                                .countryDTO(CountryDTO.builder().name("LITWA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(11)
                        .productDTO( ProductDTO.builder()
                                .name("KOMODA")
                                .price(new BigDecimal(99.99))
                                .categoryDTO(CategoryDTO.builder().name("MEBLE").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("TOOTSIE")
                                        .countryDTO(CountryDTO.builder().name("LITWA").build())
                                        .tradeDTO(TradeDTO.builder().name("KULTURA").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("EVENT")
                                .countryDTO(CountryDTO.builder().name("AUSTRALIA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(9)
                        .productDTO(ProductDTO.builder()
                                .name("SZAFA")
                                .price(new BigDecimal(654.02))
                                .categoryDTO(CategoryDTO.builder().name("MEBLE").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("TOOTSIE")
                                        .countryDTO(CountryDTO.builder().name("LITWA").build())
                                        .tradeDTO(TradeDTO.builder().name("KULTURA").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("EVENT")
                                .countryDTO(CountryDTO.builder().name("AUSTRALIA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(98)
                        .productDTO( ProductDTO.builder()
                                .name("ODKURZACZ")
                                .price(new BigDecimal(199.98))
                                .categoryDTO(CategoryDTO.builder().name("SPRZET").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("NEW SYSTEM")
                                        .countryDTO(CountryDTO.builder().name("FRANCJA").build())
                                        .tradeDTO(TradeDTO.builder().name("ZDROWIE").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("EVENT")
                                .countryDTO(CountryDTO.builder().name("AUSTRALIA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(98)
                        .productDTO(ProductDTO.builder()
                                .name("BANAN")
                                .price(new BigDecimal(8.76))
                                .categoryDTO(CategoryDTO.builder().name("OWOCE").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("MISIO")
                                        .countryDTO(CountryDTO.builder().name("AUSTRALIA").build())
                                        .tradeDTO(TradeDTO.builder().name("PRZEMYSL").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("DISCOVER")
                                .countryDTO(CountryDTO.builder().name("ROSJA").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(98)
                        .productDTO(ProductDTO.builder()
                                .name("SLONECZNIK")
                                .price(new BigDecimal(11.11))
                                .categoryDTO(CategoryDTO.builder().name("ZIARNA").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("NEW SYSTEM")
                                        .countryDTO(CountryDTO.builder().name("FRANCJA").build())
                                        .tradeDTO(TradeDTO.builder().name("ZDROWIE").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("VEGE TECH")
                                .countryDTO(CountryDTO.builder().name("CHINY").build())
                                .build())
                        .build(),
                StockDTO.builder()
                        .quantity(98)
                        .productDTO(ProductDTO.builder()
                                .name("JABLKO")
                                .price(new BigDecimal(6.77))
                                .categoryDTO(CategoryDTO.builder().name("OWOCE").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("LOGGUS")
                                        .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .shopDTO(ShopDTO.builder()
                                .name("UNIX")
                                .countryDTO(CountryDTO.builder().name("LITWA").build())
                                .build())
                        .build()
        );
    }

    public static List<CustomerOrderDTO> getCustomerOrders() {
        return Arrays.asList(
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 1, 1))
                        .discount(new BigDecimal(0.44))
                        .quantity(6)
                        .customerDTO(CustomerDTO.builder()
                                .name("MARCIN")
                                .surname("KOWAL")
                                .birthDate(LocalDate.of(1995, 1, 19))
                                .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CASH).build())
                        .productDTO(ProductDTO.builder()
                                .name("JABLKO")
                                .price(new BigDecimal(6.77))
                                .categoryDTO(CategoryDTO.builder().name("OWOCE").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("LOGGUS")
                                        .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 5, 15))
                        .discount(new BigDecimal(0.04))
                        .quantity(1)
                        .customerDTO(CustomerDTO.builder()
                                .name("MARCIN")
                                .surname("KOWAL")
                                .birthDate(LocalDate.of(1995, 1, 19))
                                .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CARD).build())
                        .productDTO(ProductDTO.builder()
                                .name("APLIKACJA")
                                .price(new BigDecimal(3223))
                                .categoryDTO(CategoryDTO.builder().name("IT").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("LOGGUS")
                                        .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 2, 15))
                        .discount(new BigDecimal(0))
                        .quantity(7)
                        .customerDTO(CustomerDTO.builder()
                                .name("KAROL")
                                .surname("DERDA")
                                .birthDate(LocalDate.of(1991, 12, 1))
                                .countryDTO(CountryDTO.builder().name("POLSKA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.MONEY_TRANSFER).build())
                        .productDTO(ProductDTO.builder()
                                .name("APLIKACJA")
                                .price(new BigDecimal(3223))
                                .categoryDTO(CategoryDTO.builder().name("IT").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("LOGGUS")
                                        .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2022, 3, 4))
                        .discount(new BigDecimal(0))
                        .quantity(4)
                        .customerDTO(CustomerDTO.builder()
                                .name("KAROL")
                                .surname("DERDA")
                                .birthDate(LocalDate.of(1991, 12, 1))
                                .countryDTO(CountryDTO.builder().name("POLSKA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.MONEY_TRANSFER).build())
                        .productDTO(ProductDTO.builder()
                                .name("APLIKACJA")
                                .price(new BigDecimal(3223))
                                .categoryDTO(CategoryDTO.builder().name("IT").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("LOGGUS")
                                        .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2021, 3, 4))
                        .discount(new BigDecimal(0.01))
                        .quantity(3)
                        .customerDTO(CustomerDTO.builder()
                                .name("KASIA")
                                .surname("MOTORSKA")
                                .birthDate(LocalDate.of(1990, 11, 2))
                                .countryDTO(CountryDTO.builder().name("POLSKA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CASH).build())
                        .productDTO(ProductDTO.builder()
                                .name("WODA")
                                .price(new BigDecimal(0.88))
                                .categoryDTO(CategoryDTO.builder().name("NAPOJE").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("LOGGUS")
                                        .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 9, 19))
                        .discount(new BigDecimal(0.11))
                        .quantity(23)
                        .customerDTO(CustomerDTO.builder()
                                .name("KASIA")
                                .surname("MOTORSKA")
                                .birthDate(LocalDate.of(1990, 11, 2))
                                .countryDTO(CountryDTO.builder().name("POLSKA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CASH).build())
                        .productDTO(ProductDTO.builder()
                                .name("NAPRAWA LAPTOPOW")
                                .price(new BigDecimal(54))
                                .categoryDTO(CategoryDTO.builder().name("IT").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("IT TECH")
                                        .countryDTO(CountryDTO.builder().name("KOREA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 8, 18))
                        .discount(new BigDecimal(0.22))
                        .quantity(22)
                        .customerDTO(CustomerDTO.builder()
                                .name("KASIA")
                                .surname("GAWRYLUK")
                                .birthDate(LocalDate.of(1992, 1, 1))
                                .countryDTO(CountryDTO.builder().name("NIEMCY").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CARD).build())
                        .productDTO(ProductDTO.builder()
                                .name("WODA")
                                .price(new BigDecimal(0.88))
                                .categoryDTO(CategoryDTO.builder().name("NAPOJE").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("LOGGUS")
                                        .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 7, 17))
                        .discount(new BigDecimal(0.14))
                        .quantity(22)
                        .customerDTO(CustomerDTO.builder()
                                .name("KASIA")
                                .surname("GAWRYLUK")
                                .birthDate(LocalDate.of(1992, 1, 1))
                                .countryDTO(CountryDTO.builder().name("NIEMCY").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CARD).build())
                        .productDTO(ProductDTO.builder()
                                .name("NAPRAWA LAPTOPOW")
                                .price(new BigDecimal(54))
                                .categoryDTO(CategoryDTO.builder().name("IT").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("IT TECH")
                                        .countryDTO(CountryDTO.builder().name("KOREA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 1, 22))
                        .discount(new BigDecimal(0.33))
                        .quantity(14)
                        .customerDTO(CustomerDTO.builder()
                                .name("OLA")
                                .surname("GLOWICKA")
                                .birthDate(LocalDate.of(1993, 4, 12))
                                .countryDTO(CountryDTO.builder().name("NIEMCY").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CARD).build())
                        .productDTO(ProductDTO.builder()
                                .name("MALUCH")
                                .price(new BigDecimal(999))
                                .categoryDTO(CategoryDTO.builder().name("SAMOCHODY").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("IT TECH")
                                        .countryDTO(CountryDTO.builder().name("KOREA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 7, 19))
                        .discount(new BigDecimal(0.09))
                        .quantity(12)
                        .customerDTO(CustomerDTO.builder()
                                .name("OLA")
                                .surname("GLOWICKA")
                                .birthDate(LocalDate.of(1993, 4, 12))
                                .countryDTO(CountryDTO.builder().name("NIEMCY").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CARD).build())
                        .productDTO(ProductDTO.builder()
                                .name("NAPRAWA LAPTOPOW")
                                .price(new BigDecimal(54))
                                .categoryDTO(CategoryDTO.builder().name("IT").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("IT TECH")
                                        .countryDTO(CountryDTO.builder().name("KOREA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 2, 11))
                        .discount(new BigDecimal(0.07))
                        .quantity(11)
                        .customerDTO(CustomerDTO.builder()
                                .name("OLA")
                                .surname("GLOWICKA")
                                .birthDate(LocalDate.of(1993, 4, 12))
                                .countryDTO(CountryDTO.builder().name("NIEMCY").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.MONEY_TRANSFER).build())
                        .productDTO(ProductDTO.builder()
                                .name("FIAT")
                                .price(new BigDecimal(9999))
                                .categoryDTO(CategoryDTO.builder().name("SAMOCHODY").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("DISCOVER")
                                        .countryDTO(CountryDTO.builder().name("ROSJA").build())
                                        .tradeDTO(TradeDTO.builder().name("TRANSPORT").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 3, 3))
                        .discount(new BigDecimal(0.05))
                        .quantity(4)
                        .customerDTO(CustomerDTO.builder()
                                .name("ALA")
                                .surname("KISZLO")
                                .birthDate(LocalDate.of(1994, 4, 3))
                                .countryDTO(CountryDTO.builder().name("USA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.MONEY_TRANSFER).build())
                        .productDTO(ProductDTO.builder()
                                .name("MARCHEW")
                                .price(new BigDecimal(3.32))
                                .categoryDTO(CategoryDTO.builder().name("WARZYWA").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("DISCOVER")
                                        .countryDTO(CountryDTO.builder().name("ROSJA").build())
                                        .tradeDTO(TradeDTO.builder().name("TRANSPORT").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 9, 9))
                        .discount(new BigDecimal(0.07))
                        .quantity(5)
                        .customerDTO(CustomerDTO.builder()
                                .name("ALA")
                                .surname("KISZLO")
                                .birthDate(LocalDate.of(1994, 4, 3))
                                .countryDTO(CountryDTO.builder().name("USA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.MONEY_TRANSFER).build())
                        .productDTO(ProductDTO.builder()
                                .name("BUS")
                                .price(new BigDecimal(14876))
                                .categoryDTO(CategoryDTO.builder().name("SAMOCHODY").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("VEGE TECH")
                                        .countryDTO(CountryDTO.builder().name("NIEMCY").build())
                                        .tradeDTO(TradeDTO.builder().name("HANDEL").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 8, 8))
                        .discount(new BigDecimal(0.03))
                        .quantity(6)
                        .customerDTO(CustomerDTO.builder()
                                .name("MARCIN")
                                .surname("KOWAL")
                                .birthDate(LocalDate.of(1995, 1, 19))
                                .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.MONEY_TRANSFER).build())
                        .productDTO(ProductDTO.builder()
                                .name("MALUCH")
                                .price(new BigDecimal(999))
                                .categoryDTO(CategoryDTO.builder().name("SAMOCHODY").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("IT TECH")
                                        .countryDTO(CountryDTO.builder().name("KOREA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 7, 7))
                        .discount(new BigDecimal(0.77))
                        .quantity(7)
                        .customerDTO(CustomerDTO.builder()
                                .name("FRANEK")
                                .surname("KOWAL")
                                .birthDate(LocalDate.of(1999, 2, 16))
                                .countryDTO(CountryDTO.builder().name("AUSTRALIA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CASH).build())
                        .productDTO(ProductDTO.builder()
                                .name("FIAT")
                                .price(new BigDecimal(9999))
                                .categoryDTO(CategoryDTO.builder().name("SAMOCHODY").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("DISCOVER")
                                        .countryDTO(CountryDTO.builder().name("ROSJA").build())
                                        .tradeDTO(TradeDTO.builder().name("TRANSPORT").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 6, 6))
                        .discount(new BigDecimal(0.21))
                        .quantity(32)
                        .customerDTO(CustomerDTO.builder()
                                .name("PAWEL")
                                .surname("WARCHOL")
                                .birthDate(LocalDate.of(1995, 3, 8))
                                .countryDTO(CountryDTO.builder().name("USA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CASH).build())
                        .productDTO(ProductDTO.builder()
                                .name("LAPTOP")
                                .price(new BigDecimal(4449.9))
                                .categoryDTO(CategoryDTO.builder().name("ELEKTRONIKA").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("VEGE TECH")
                                        .countryDTO(CountryDTO.builder().name("NIEMCY").build())
                                        .tradeDTO(TradeDTO.builder().name("HANDEL").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 11, 12))
                        .discount(new BigDecimal(0.25))
                        .quantity(11)
                        .customerDTO(CustomerDTO.builder()
                                .name("WOJTEK")
                                .surname("GRYSIAK")
                                .birthDate(LocalDate.of(1981, 3, 30))
                                .countryDTO(CountryDTO.builder().name("CHINY").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CASH).build())
                        .productDTO(ProductDTO.builder()
                                .name("KOMORKA")
                                .price(new BigDecimal(2998.77))
                                .categoryDTO(CategoryDTO.builder().name("ELEKTRONIKA").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("UNIX")
                                        .countryDTO(CountryDTO.builder().name("LITWA").build())
                                        .tradeDTO(TradeDTO.builder().name("NAUKA").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2019, 3, 4))
                        .discount(new BigDecimal(0.27))
                        .quantity(4)
                        .customerDTO(CustomerDTO.builder()
                                .name("WOJTEK")
                                .surname("GRYSIAK")
                                .birthDate(LocalDate.of(1981, 3, 30))
                                .countryDTO(CountryDTO.builder().name("CHINY").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CARD).build())
                        .productDTO(ProductDTO.builder()
                                .name("TELEWIZOR")
                                .price(new BigDecimal(1888.88))
                                .categoryDTO(CategoryDTO.builder().name("ELEKTRONIKA").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("UNIX")
                                        .countryDTO(CountryDTO.builder().name("LITWA").build())
                                        .tradeDTO(TradeDTO.builder().name("NAUKA").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2019, 3, 4))
                        .discount(new BigDecimal(0.28))
                        .quantity(15)
                        .customerDTO(CustomerDTO.builder()
                                .name("ZBYSZEK")
                                .surname("TOMASZEWSKI")
                                .birthDate(LocalDate.of(1981, 3, 28))
                                .countryDTO(CountryDTO.builder().name("AUSTRALIA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CARD).build())
                        .productDTO(ProductDTO.builder()
                                .name("KOMODA")
                                .price(new BigDecimal(99.99))
                                .categoryDTO(CategoryDTO.builder().name("MEBLE").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("TOOTSIE")
                                        .countryDTO(CountryDTO.builder().name("LITWA").build())
                                        .tradeDTO(TradeDTO.builder().name("KULTURA").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 1, 4))
                        .discount(new BigDecimal(0.27))
                        .quantity(5)
                        .customerDTO(CustomerDTO.builder()
                                .name("ALEKS")
                                .surname("NOWAK")
                                .birthDate(LocalDate.of(1971, 2, 23))
                                .countryDTO(CountryDTO.builder().name("AUSTRALIA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CARD).build())
                        .productDTO(ProductDTO.builder()
                                .name("SZAFA")
                                .price(new BigDecimal(654.02))
                                .categoryDTO(CategoryDTO.builder().name("MEBLE").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("TOOTSIE")
                                        .countryDTO(CountryDTO.builder().name("LITWA").build())
                                        .tradeDTO(TradeDTO.builder().name("KULTURA").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 2, 4))
                        .discount(new BigDecimal(0.17))
                        .quantity(2)
                        .customerDTO(CustomerDTO.builder()
                                .name("ALEKS")
                                .surname("NOWAK")
                                .birthDate(LocalDate.of(1971, 2, 23))
                                .countryDTO(CountryDTO.builder().name("AUSTRALIA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CARD).build())
                        .productDTO(ProductDTO.builder()
                                .name("ODKURZACZ")
                                .price(new BigDecimal(199.98))
                                .categoryDTO(CategoryDTO.builder().name("SPRZET").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("NEW SYSTEM")
                                        .countryDTO(CountryDTO.builder().name("FRANCJA").build())
                                        .tradeDTO(TradeDTO.builder().name("ZDROWIE").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2019, 6, 6))
                        .discount(new BigDecimal(0.04))
                        .quantity(3)
                        .customerDTO(CustomerDTO.builder()
                                .name("PAWEL")
                                .surname("WARCHOL")
                                .birthDate(LocalDate.of(1995, 3, 8))
                                .countryDTO(CountryDTO.builder().name("USA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.MONEY_TRANSFER).build())
                        .productDTO(ProductDTO.builder()
                                .name("BANAN")
                                .price(new BigDecimal(8.76))
                                .categoryDTO(CategoryDTO.builder().name("OWOCE").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("MISIO")
                                        .countryDTO(CountryDTO.builder().name("AUSTRALIA").build())
                                        .tradeDTO(TradeDTO.builder().name("PRZEMYSL").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2020, 2, 29))
                        .discount(new BigDecimal(0.07))
                        .quantity(2)
                        .customerDTO(CustomerDTO.builder()
                                .name("OLA")
                                .surname("GLOWICKA")
                                .birthDate(LocalDate.of(1993, 4, 12))
                                .countryDTO(CountryDTO.builder().name("NIEMCY").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.MONEY_TRANSFER).build())
                        .productDTO(ProductDTO.builder()
                                .name("SLONECZNIK")
                                .price(new BigDecimal(11.11))
                                .categoryDTO(CategoryDTO.builder().name("ZIARNA").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("NEW SYSTEM")
                                        .countryDTO(CountryDTO.builder().name("FRANCJA").build())
                                        .tradeDTO(TradeDTO.builder().name("ZDROWIE").build())
                                        .build())
                                .build())
                        .build(),
                CustomerOrderDTO.builder()
                        .date(LocalDate.of(2019, 9, 9))
                        .discount(new BigDecimal(0.1))
                        .quantity(1)
                        .customerDTO(CustomerDTO.builder()
                                .name("MARCIN")
                                .surname("KOWAL")
                                .birthDate(LocalDate.of(1995, 1, 19))
                                .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                .build())
                        .paymentDTO(PaymentDTO.builder().ePayment(EPayment.CARD).build())
                        .productDTO(ProductDTO.builder()
                                .name("JABLKO")
                                .price(new BigDecimal(6.77))
                                .categoryDTO(CategoryDTO.builder().name("OWOCE").build())
                                .producerDTO(ProducerDTO.builder()
                                        .name("LOGGUS")
                                        .countryDTO(CountryDTO.builder().name("HISZPANIA").build())
                                        .tradeDTO(TradeDTO.builder().name("ROLNICTWO").build())
                                        .build())
                                .build())
                        .build()
        );
    }

}
